### ISSUE TITLE
[suggestion] Android demo screenshot

### ISSUE THREAD

**Issue by lucasferreira** [michaelhelvey/react-native-forms#1]
Hi @michaelhelvey 

Your library seems to be awesome! 

Is it possible to add in README the same demo screenshot but running in Android?

Just to compare the render of both platforms.

Thanks ;)

**Comment by michaelhelvey** [comment]
Currently, the library renders basically the same on Android as it does on iOS, with a couple exceptions (for example, `TextInput` looks a little different, and `TextInput`'s `multiline` prop doesn't work the same way on Android.)

I'm a native iOS developer, and don't have much experience with what a good native Android form _should_ look like, so I'm kind of hoping for PR's from those who could really spruce that up.  But for reference, I went ahead and updated the README.  :)

Thanks for the input!
